[monitoring_servers]
# Replace with your ECS public or private IP addresses.
YOUR_SERVER_IP ansible_user=root
# 192.168.1.11 ansible_user=root
# 192.168.1.12 ansible_user=ecs-user ansible_become=true

[monitoring_servers:vars]
ansible_python_interpreter=/usr/bin/python3

